### ISSUE TITLE
using flink-sql-connector-mysql-cdc-2.3.0 to query mysql database data has a time zone problem

### ISSUE THREAD

**Issue by zengqinglei** [ververica/flink-cdc-connectors#1954]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.3.0

### Database and its version

mysql 5.7

timezone：UTC +08:00

![image](https://user-images.githubusercontent.com/7374317/222023884-908d9bb3-2678-4f9e-be75-629a4b3175ea.png)

### Minimal reproduce step

Use the k8s cluster to deploy the session mode of flink：
1. define flink-configuration-configmap.yaml
``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flink
  name: flink-config
  labels:
    app: flink
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 20
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    queryable-state.proxy.ports: 6125
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    parallelism.default: 2
    env.java.opts.taskmanager: "-Duser.timezone=Asia/Shanghai"
    env.java.opts.jobmanager: "-Duser.timezone=Asia/Shanghai"
  log4j-console.properties: |+
    # 如下配置会同时影响用户代码和 Flink 的日志行为
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    rootLogger.appenderRef.rolling.ref = RollingFileAppender

    # 如果你只想改变 Flink 的日志行为则可以取消如下的注释部分
    #logger.flink.name = org.apache.flink
    #logger.flink.level = INFO

    # 下面几行将公共 libraries 或 connectors 的日志级别保持在 INFO 级别。
    # root logger 的配置不会覆盖此处配置。
    # 你必须手动修改这里的日志级别。
    logger.akka.name = akka
    logger.akka.level = INFO
    logger.kafka.name= org.apache.kafka
    logger.kafka.level = INFO
    logger.hadoop.name = org.apache.hadoop
    logger.hadoop.level = INFO
    logger.zookeeper.name = org.apache.zookeeper
    logger.zookeeper.level = INFO

    # 将所有 info 级别的日志输出到 console
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

    # 将所有 info 级别的日志输出到指定的 rolling file
    appender.rolling.name = RollingFileAppender
    appender.rolling.type = RollingFile
    appender.rolling.append = false
    appender.rolling.fileName = ${sys:log.file}
    appender.rolling.filePattern = ${sys:log.file}.%i
    appender.rolling.layout.type = PatternLayout
    appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    appender.rolling.policies.type = Policies
    appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
    appender.rolling.policies.size.size=100MB
    appender.rolling.strategy.type = DefaultRolloverStrategy
    appender.rolling.strategy.max = 10

    # 关闭 Netty channel handler 中不相关的（错误）警告
    logger.netty.name = org.jboss.netty.channel.DefaultChannelPipeline
    logger.netty.level = OFF
```
2. define jobmanager-service.yaml
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: flink
    component: jobmanager
```
3. define jobmanager-rest-service.yaml
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: flink
    component: jobmanager
```
4. define jobmanager-session-deployment-non-ha.yaml
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flink
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: apache/flink:latest
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        env:
        - name: LANG
          value: zh_CN.UTF-8
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: localtime
          mountPath: /etc/localtime
        - name: flink-connector-jdbc
          mountPath: /opt/flink/lib/flink-connector-jdbc-1.16.1.jar
        - name: flink-mysql-cdc
          mountPath: /opt/flink/lib/flink-sql-connector-mysql-cdc-2.3.0.jar
        - name: flink-sqlserver-cdc
          mountPath: /opt/flink/lib/flink-sql-connector-sqlserver-cdc-2.3.0.jar
        securityContext:
          runAsUser: 9999  # 参考官方 flink 镜像中的 _flink_ 用户，如有必要可以修改
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: flink-connector-jdbc
        hostPath:
          path: /nfs/data/kubernetes/flink/lib/flink-connector-jdbc-1.16.1.jar
      - name: flink-mysql-cdc
        hostPath:
          path: /nfs/data/kubernetes/flink/lib/flink-sql-connector-mysql-cdc-2.3.0.jar
      - name: flink-sqlserver-cdc
        hostPath:
          path: /nfs/data/kubernetes/flink/lib/flink-sql-connector-sqlserver-cdc-2.3.0.jar
```
5. define taskmanager-session-deployment.yaml
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flink
  name: flink-taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: apache/flink:latest
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
        env:
        - name: LANG
          value: zh_CN.UTF-8
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
        - name: localtime
          mountPath: /etc/localtime
        - name: flink-connector-jdbc
          mountPath: /opt/flink/lib/flink-connector-jdbc-1.16.1.jar
        - name: flink-mysql-cdc
          mountPath: /opt/flink/lib/flink-sql-connector-mysql-cdc-2.3.0.jar
        - name: flink-sqlserver-cdc
          mountPath: /opt/flink/lib/flink-sql-connector-sqlserver-cdc-2.3.0.jar
        securityContext:
          runAsUser: 9999  # 参考官方 flink 镜像中的 _flink_ 用户，如有必要可以修改
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: flink-connector-jdbc
        hostPath:
          path: /nfs/data/kubernetes/flink/lib/flink-connector-jdbc-1.16.1.jar
      - name: flink-mysql-cdc
        hostPath:
          path: /nfs/data/kubernetes/flink/lib/flink-sql-connector-mysql-cdc-2.3.0.jar
      - name: flink-sqlserver-cdc
        hostPath:
          path: /nfs/data/kubernetes/flink/lib/flink-sql-connector-sqlserver-cdc-2.3.0.jar
```
6. deploy flink in k8s cluster
``` yaml
kubectl apply -f flink-configuration-configmap.yaml
kubectl apply -f jobmanager-service.yaml
kubectl apply -f jobmanager-rest-service.yaml
kubectl apply -f jobmanager-session-deployment-non-ha.yaml
kubectl apply -f taskmanager-session-deployment.yaml
```
7、create a table products in the mysql database and add test data
``` sql
-- MySQL
CREATE DATABASE mydb;
USE mydb;
CREATE TABLE products (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512)
);
ALTER TABLE products AUTO_INCREMENT = 101;
 
INSERT INTO products
VALUES (default,"scooter","Small 2-wheel scooter"),
       (default,"car battery","12V car battery"),
       (default,"12-pack drill bits","12-pack of drill bits with sizes ranging from #40 to #3"),
       (default,"hammer","12oz carpenter's hammer"),
       (default,"hammer","14oz carpenter's hammer"),
       (default,"hammer","16oz carpenter's hammer"),
       (default,"rocks","box of assorted rocks"),
       (default,"jacket","water resistent black wind breaker"),
       (default,"spare tire","24 inch spare tire");
```
8. enter the pod of jobmanager and start a job using sql-client
``` bash
kubectl exec -it <jobmanager-pod-name> -n <flink-namespace> /bin/bash
./bin/sql-client
----------------------------------------------------
CREATE TABLE products (
    id INT,
    name STRING,
    description STRING,
    PRIMARY KEY (id) NOT ENFORCED
  ) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = '10.20.180.3',
    'port' = '3306',
    'username' = 'root',
    'password' = 'LiD2Ax3MIsD',
    'database-name' = 'mydb',
    'table-name' = 'products'
);
----------------------------------------------------
select * from products;
```

### What did you expect to see?

![image](https://user-images.githubusercontent.com/7374317/222027144-3d61e26d-d210-401f-814a-2df0e6c1c518.png)

### What did you see instead?

![image](https://user-images.githubusercontent.com/7374317/222027439-a9dbabc5-6996-47fd-862b-550ce364f857.png)

### Anything else?

I tried to use flink-sql-connector-mysql-cdc-2.2.1 without encountering the above problem

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
